#!/usr/bin/env python3
"""
Turn the application icon into a C header the GUI can embed.

SDL3 core has no image decoder, so the window icon has to reach SDL as raw
pixels on an SDL_Surface. Shipping 144x144 RGBA (83 KB) as a C array would
be absurd for a picture that uses exactly two colours, so this packs it
1 bit per pixel, MSB first, rows padded to a byte - 2592 bytes - and
src/gui/icon.cpp expands it back to RGBA at startup.

The generated header is checked in, so a plain `make` needs no Python and
no Pillow. Re-run this only when assets/icon/p2500icon.png changes:

    tools/mk_icon.py assets/icon/p2500icon.png -o src/gui/icon_data.h

The input must be strictly two-coloured; anything else is a mistake worth
stopping for rather than silently thresholding, since the icon is meant to
be the machine's own 1-bit look.
"""

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("needs Pillow: pacman -S python-pillow")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", type=Path, help="source PNG (two colours only)")
    ap.add_argument("-o", "--output", type=Path, required=True, help="header to write")
    ap.add_argument("--name", default="p2500_icon", help="C identifier prefix")
    args = ap.parse_args()

    img = Image.open(args.input).convert("RGB")
    w, h = img.size
    colours = img.getcolors(maxcolors=16)
    if colours is None or len(colours) != 2:
        n = "more than 16" if colours is None else len(colours)
        sys.exit(f"{args.input}: expected exactly 2 colours, found {n}. "
                 "The icon is a 1-bit image by design - fix the source "
                 "rather than relaxing this check.")

    # The set bit is the lighter colour: "ink" on the P2500's black screen.
    lum = lambda c: 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2]
    dark, light = sorted((c for _, c in colours), key=lum)

    stride = (w + 7) // 8
    bits = bytearray(stride * h)
    px = img.load()
    for y in range(h):
        for x in range(w):
            if px[x, y] == light:
                bits[y * stride + (x >> 3)] |= 0x80 >> (x & 7)

    rows = []
    for i in range(0, len(bits), 12):
        rows.append("    " + " ".join(f"0x{b:02X}," for b in bits[i:i + 12]))
    body = "\n".join(rows)
    guard = f"{args.name.upper()}_DATA_H"

    args.output.write_text(f"""/*
 * Generated by tools/mk_icon.py from {args.input.as_posix()} - do not edit.
 *
 * {w}x{h}, 1 bit per pixel, MSB first, rows padded to a byte. Set bit =
 * foreground. src/gui/icon.cpp expands this to RGBA for SDL_SetWindowIcon.
 */
#ifndef {guard}
#define {guard}

#define {args.name.upper()}_WIDTH  {w}
#define {args.name.upper()}_HEIGHT {h}
#define {args.name.upper()}_FG 0x{light[0]:02X}, 0x{light[1]:02X}, 0x{light[2]:02X}
#define {args.name.upper()}_BG 0x{dark[0]:02X}, 0x{dark[1]:02X}, 0x{dark[2]:02X}

static const unsigned char {args.name}_bits[] = {{
{body}
}};

#endif
""")
    print(f"{args.output}: {w}x{h}, {len(bits)} bytes of bitmap "
          f"(fg #{light[0]:02x}{light[1]:02x}{light[2]:02x}, "
          f"bg #{dark[0]:02x}{dark[1]:02x}{dark[2]:02x})")


if __name__ == "__main__":
    main()
