#!/usr/bin/env python3
"""
Turn an image into a pre-shifted 1-bit sprite for the P2500's graphics mode.

Pre-shifted because horizontal movement has to be smooth. Video memory is
addressed a byte at a time, so a sprite drawn straight out of its own bitmap
can only move in 8-pixel steps. Holding eight copies - the same picture
shifted 0 to 7 pixels right, each one byte wider - buys single-pixel motion
for the cost of a table lookup, which is the trade every machine of this era
made.

Emits Z80 source for tools/z80asm.py: shift-major, so the eight copies are
contiguous and the drawing code picks one with a multiply by
(height * bytes_per_row).

    tools/mk_sprite.py IN.png OUT.asm --name logo --width 112 [--crop-x 0.62]
                       [--threshold 128] [--preview]
"""

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("needs Pillow: pacman -S python-pillow")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("output")
    ap.add_argument("--name", default="sprite")
    ap.add_argument("--width", type=int, default=112)
    ap.add_argument("--crop-x", type=float, default=1.0,
                    help="keep this fraction of the width before trimming")
    ap.add_argument("--threshold", type=int, default=128)
    ap.add_argument("--invert", action="store_true",
                    help="light pixels are ink, not dark ones")
    ap.add_argument("--halo", action="store_true",
                    help="surround the sprite with one byte of transparent "
                         "margin left and right and one row top and bottom, so "
                         "a mover can be drawn with a plain store and no erase")
    ap.add_argument("--preview", action="store_true")
    args = ap.parse_args()

    im = Image.open(args.source).convert("RGBA")
    # An alpha channel is the mask when there is one; otherwise ink is dark.
    alpha = im.split()[3]
    mask = alpha if alpha.getextrema() != (255, 255) else \
        im.convert("L").point(lambda v: 255 - v)
    if args.invert:
        mask = mask.point(lambda v: 255 - v)
    if args.crop_x < 1.0:
        mask = mask.crop((0, 0, int(mask.size[0] * args.crop_x), mask.size[1]))
    bb = mask.getbbox()
    if bb:
        mask = mask.crop(bb)

    h = max(1, round(mask.size[1] * args.width / mask.size[0]))
    # Bilinear, not Lanczos: sharpening ringing around a hard edge turns into
    # speckle once it is thresholded to one bit.
    small = mask.resize((args.width, h), Image.BILINEAR)
    px = small.load()
    rows = [[px[x, y] > args.threshold for x in range(args.width)] for y in range(h)]

    # Trim fully blank rows and columns - a border of nothing costs bytes in
    # every one of the eight copies.
    while rows and not any(rows[0]):
        rows.pop(0)
    while rows and not any(rows[-1]):
        rows.pop()
    left = min((r.index(True) for r in rows if any(r)), default=0)
    right = max((len(r) - 1 - r[::-1].index(True) for r in rows if any(r)), default=0)
    rows = [r[left:right + 1] for r in rows]
    w, h = len(rows[0]), len(rows)
    bw = (w + 7) // 8 + 1          # one spare byte for the shifted-in edge

    if args.halo:
        # A sprite that steps one pixel a field can be drawn with a plain
        # store instead of erase-then-draw, provided it carries enough
        # background of its own to cover where it just was. One byte each
        # side horizontally (the blit is byte-aligned) and one row top and
        # bottom is exactly enough - and it halves the work, because every
        # byte is now written once with its final value rather than twice.
        rows = [[False] * 8 + r + [False] * 8 for r in rows]
        rows = [[False] * len(rows[0])] + rows + [[False] * len(rows[0])]
        w, h = len(rows[0]), len(rows)
        bw = (w + 7) // 8 + 1

    if args.preview:
        for r in rows:
            print("  " + "".join("#" if v else "." for v in r))

    out = [f"; Generated by tools/mk_sprite.py from {Path(args.source).name}",
           f"; {w} x {h} pixels, {bw} bytes per row, 8 pre-shifted copies."]
    if args.halo:
        out += ["; Haloed: a blank byte each side and a blank row top and "
                "bottom, so a mover",
                "; that steps within that margin can be drawn with a plain "
                "store and no erase."]
    out += [
           f"{args.name}_w   equ {bw}",
           f"{args.name}_h   equ {h}",
           f"{args.name}_pix equ {w}",
           f"{args.name}_sz  equ {bw * h}",
           f"{args.name}:"]
    for shift in range(8):
        out.append(f"; --- shifted right {shift} pixel(s)")
        for r in rows:
            bits = [False] * shift + list(r)
            bits += [False] * (bw * 8 - len(bits))
            data = []
            for b in range(bw):
                v = 0
                for i in range(8):
                    if bits[b * 8 + i]:
                        v |= 0x80 >> i
                data.append(v)
            out.append("  db " + ",".join(f"${v:02X}" for v in data))
    Path(args.output).write_text("\n".join(out) + "\n")
    print(f"{args.output}: {w}x{h} px, {bw} bytes/row, "
          f"{bw * h} bytes per copy, {bw * h * 8} total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
